=== gematik/api-erp/resources/examples/ti-dienste/communication/json-schema_DispReq.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "version": {
      "type": "integer",
      "enum": [2]
    },
    "supplyOptionsType": {
      "type": "string",
      "enum": ["onPremise", "shipment", "delivery"]
    },
    "name": {
      "type": "string",
      "maxLength": 50
    },
    "address": {
      "type": "string",
      "maxLength": 500
    },
    "hint": {
      "type": "string",
      "maxLength": 500
    },
    "text": {
      "type": "string",
      "maxLength": 500
    },
    "phone": {
      "type": "string",
      "maxLength": 32
    },
    "mail": {
      "type": "string"
    },
    "transactionID": {
      "type": "string"
    },
    "taskID": {
      "type": "string",
      "maxLength": 500
    },
    "accessCode": {
      "type": "string",
      "maxLength": 25
    }
  },
  "required": [
    "version",
    "supplyOptionsType",
    "transactionID",
    "taskID",
    "accessCode"
  ]
}

=== gematik/api-erp/resources/examples/ti-dienste/communication/json-contentString-DispReq.json
{
  "version": 2,
  "supplyOptionsType": "delivery",
  "name": "Dr. Peter Lustig",
  "address": "Am LÃ¶wenzahn 4, 14482 Potsdam",
  "hint": "Bitte am Bauwagen klopfen",
  "text": "Stellen Sie mir bitte folgendes Medikament zu",
  "phone": "0179 123456",
  "mail": "peter.lustig@mail.de",
  "transactionID": "0091a0b6-15e8-4110-acde-21b6bd50b54a",
  "taskID": "160.123.456.789.123.58",
  "accessCode": "777bea0e13cc9c42ceec14aec3ddee2263325dc2c6c699db115f58fe423607ea"
}
